// Code generated by mockery. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// BodyMarshaler is an autogenerated mock type for the BodyMarshaler type
type BodyMarshaler struct {
	mock.Mock
}

// Execute provides a mock function with given fields: v, ct
func (_m *BodyMarshaler) Execute(v interface{}, ct *string) ([]byte, error) {
	ret := _m.Called(v, ct)

	var r0 []byte
	if rf, ok := ret.Get(0).(func(interface{}, *string) []byte); ok {
		r0 = rf(v, ct)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(interface{}, *string) error); ok {
		r1 = rf(v, ct)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
